name: Setup Node
description: Setup node and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .tool-versions
        cache: npm
    - run: npm install --frozen-lockfile
      shell: bash
