# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'github-actions'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod-js-dependencies:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
        exclude-patterns:
          - '*native*'
      prod-native-dependencies:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
        patterns:
          - '*native*'
        exclude-patterns:
          - 'react-native'
