require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :deterministic_uuids => false
prepare_react_native_project!

production = ENV["PRODUCTION"] == "1"

target 'RBSCVCA-tvOS' do

  platform :tvos, min_ios_version_supported

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

post_install do |installer|
  react_native_post_install(
    installer,
    # Set `mac_catalyst_enabled` to `true` in order to apply patches
    # necessary for Mac Catalyst builds
    :mac_catalyst_enabled => false
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  %x(
    if ! patch -R -p0 -s -f --dry-run Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/tvos-arm64/hermes.framework/Info.plist < hermes-engine.patch; then
      patch -p0 Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/tvos-arm64/hermes.framework/Info.plist < hermes-engine.patch
    fi
  )
end