# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

platform :ios do
  before_all do
    app_store_connect_api_key(
      key_id: "H9DC9YSR79",
      issuer_id: "46325a56-6b53-468b-8257-0cda3768945d",
      key_filepath: "fastlane/AuthKey_H9DC9YSR79.p8",
    )
  end

  desc "Push a new test build to TestFlight"
  lane :publish_internal_test do
    increment_build_number(xcodeproj: "ios/RBSCVCA.xcodeproj", skip_info_plist: true)
    build_app(workspace: "ios/RBSCVCA.xcworkspace", scheme: "RBSCVCA-tvOS", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end
end

platform :android do
  desc "Push a new test build to Play Store"
  lane :publish_internal_test do
    android_set_version_code(gradle_file: "android/app/build.gradle")
    gradle(project_dir: "android", task: "bundle", build_type: "Release")
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      skip_upload_apk: true,
    )
  end
end
