# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

platform :ios do
  before_all do
    app_store_connect_api_key(
      key_id: "H9DC9YSR79",
      issuer_id: "46325a56-6b53-468b-8257-0cda3768945d",
      key_filepath: "fastlane/AuthKey_H9DC9YSR79.p8",
    )
  end

  desc "Push a new test build to TestFlight"
  lane :publish_internal_test do
    increment_build_number(xcodeproj: "ios/RBSCVCA.xcodeproj", skip_info_plist: true)
    build_app(workspace: "ios/RBSCVCA.xcworkspace", scheme: "RBSCVCA-tvOS", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end

  desc "Publish the latest build to open testing"
  lane :publish_open_test do
    build_number = get_build_number(xcodeproj: "ios/RBSCVCA.xcodeproj")
    testflight(
      build_number: build_number,
      distribute_only: true,
      distribute_external: true,
      groups: ["Rocket Beans", "Rocket Beans Community"],
    )
  end

  desc "Publish the latest build to production"
  lane :publish_production do
    build_number = get_build_number(xcodeproj: "ios/RBSCVCA.xcodeproj")
    deliver(
      build_number: build_number,
      skip_binary_upload: true,
      skip_screenshots: true,
      run_precheck_before_submit: false,
      force: true,
    )
  end
end

platform :android do
  desc "Push a new test build to Play Store"
  lane :publish_internal_test do
    android_set_version_code(gradle_file: "android/app/build.gradle")
    gradle(project_dir: "android", task: "bundle", build_type: "Release")
    upload_to_play_store(
      track: "internal",
      skip_upload_apk: true,
    )
  end

  desc "Publish the latest build to open testing"
  lane :publish_open_test do
    version_code = android_get_version_code(gradle_file: "android/app/build.gradle")
    supply(
      version_code: version_code,
      track_promote_to: "beta",
      skip_upload_apk: true,
      skip_upload_aab: true,
    )
  end

  desc "Publish the latest build to production"
  lane :publish_production do
    version_code = android_get_version_code(gradle_file: "android/app/build.gradle")
    supply(
      version_code: version_code,
      track_promote_to: "production",
      skip_upload_apk: true,
      skip_upload_aab: true,
    )
  end
end
